stealjs/steal

- README.md
Link pointed to local development version
> Fix link to contributing and developing

- docs/module-config.md
- docs/module-css.md
- docs/module-less.md
- docs/module-loader.md
- docs/module-npm.md
- docs/pages/contributing.md
- docs/steal.md
- docs/syntax-commonjs.md
- docs/syntax-es6.md
- docs/system-baseURL.md
- docs/system-bowerDev.md
- docs/system-bowerPath.md
- docs/system-buildConfig.md
- docs/system-bundle.md
- docs/system-bundles.md
- docs/system-bundlesPath.md
- docs/system-configPath.md
- docs/system-env.md
- docs/system-ext.md
- docs/system-instantiated.md
- docs/system-lessOptions.md
- docs/system-main.md
- docs/system-map.md
- docs/system-paths.md
- docs/system-stealPath.md
- docs/type-metadata.md
Fixing syntax, examples, typos and adding new documentation for client side Steal. #251 #240 #236 #235
> Updated client side documentation

- docs/system-transpiler.md
Fixes #323
Depends on https://github.com/bitovi/steal-tools/pull/159
> Document use of System.transpiler

- docs/pages/project-exporting.md
Several updates to the export process
Expand export introductory description.
Clarify the steal-export grunt task and steal-tools.export relationship
Clarify the system.config and system.main properties
Fix a few typos and general wording
> Update Project Exporting Guide

- ext/npm-extension.js
- ext/npm-utils.js
- ext/npm.js
- package.json
- steal.production.js
- test/ext/npm.js
Changes the npm extension for https://github.com/bitovi/system-npm/issues/7.  Make sure that if this works, we update the package.jsons to a version.
> changes how directories lib works

- ext/npm-extension.js
- ext/npm-utils.js
- ext/npm.js
- package.json
- test/ext/npm.js
- test/npm/package.json
- test/test.js
Includes fixes to make directories.lib work when loading from `System.main`.
PR is waiting there: https://github.com/bitovi/system-npm/pull/12
> Newest build of system-npm

- bower.json
- ext/traceur.js
- steal.production.js
- test/ext/traceur.js
> Upgrade to the latest traceur

- docs/module-npm.md
- docs/pages/quick-start.md
The sentence "Install Node.js on your computer and that grunt-cli is installed globally" bothered me so I made a small edit, plus a couple other tweaks.
> Minor wording improvements.

- ext/npm-extension.js
- ext/npm.js
- test/ext/npm.js
This upgrades our system-npm to 0.1.8 which included a fix for contextual maps.
> Upgrade to system-npm 0.1.8

- docs/system-lessOptions.md
- ext/less.js
Add support for lessOptions.paths option and docs updated
> Add support for lessOptions.paths option

- docs/module-npm.md
- ext/npm-crawl.js
- ext/npm.js
- package.json
- test/ext/npm.js
This upgrades steal to use system-npm 0.2.0.
Fixes #392 and #393
> Upgrade to system-npm 0.2.0

- ext/npm-extension.js
includes a meta config conversion fix.
> Upgrade to system-npm 0.2.3

- ext/live-reload.js
- ext/npm.js
- package.json
- test/ext/npm.js
> Update system-npm and system-live-reload

- ext/npm.js
- test/ext/npm.js
This updates us to system-npm 0.3.2, fix for live-reload scenarios.
> Update to system-npm 0.3.2

- ext/live-reload.js
- package.json
This includes a fix for orphaned modules
> Upgrade live-reload to 1.0.1

- docs/steal-done.md
This adds docs for steal.done, fixes #489
> Document steal.done

- docs/module-less.md
- docs/stealjs.md
- docs/syntax-es6.md
- docs/syntax-global.md
I found them while working on #438.
> Fix some typos.

- package.json
> Update npm dependency of systemjs

- package.json
Just testing to see if this breaks any tests or not.
> Test against system-npm wildcard paths branch

- package.json
> Add keywords to the package

- ext/npm-crawl.js
- package.json
It includes a fix for the npm3 algorithm: https://github.com/stealjs/system-npm/pull/87
> Update to system-npm 0.4.1

- ext/css.js
- package.json
- test/ext/css.js
> Update steal-css for env fix

- ext/npm-load.js
- ext/npm.js
- package.json
- test/ext/npm.js
This includes a fix needed for https://github.com/stealjs/steal-tools/issues/365
> Upgrade to system-npm 0.5.1

- ext/npm-load.js
- package.json
This includes a fix for https://github.com/stealjs/steal/issues/588
> Upgrade to system-npm 0.5.5

- src/core.js
- src/start.js
This is for steal-tools issue: https://github.com/stealjs/steal-tools/issues/198
> fileUrls are relative

- ext/npm-convert.js
- ext/npm-utils.js
- ext/npm.js
- package.json
- test/ext/npm.js
Fixes https://github.com/stealjs/steal-tools/issues/198
> Upgrade to system-npm 0.5.6

- index.html
I think this will fix the hub on the home page, which is currently broken.  Correct me if I'm wrong.  :)
> Fix BitHub link

- ext/npm-utils.js
- package.json
> Upgrade to system-npm 0.5.10

- main.js
- src/config.js
- steal.js
This is from https://github.com/stealjs/steal/pull/633
> Allow not setting the env when steal is bundled in production

- ext/css.js
- package.json
- test/ext/css.js
This fixes an issue with using `locate://` cc @akagomez
> Upgrade to steal-css 0.4.1

- ext/npm-convert.js
- ext/npm-utils.js
- ext/npm.js
- package.json
- test/ext/npm.js
> Upgrade to system-npm 0.6.3

- docs/hook-fetch.md
- docs/hook-instantiate.md
- docs/hook-locate.md
- docs/hook-normalize.md
- docs/hook-translate.md
- docs/pages/writing-plugins.md
- docs/type-instantiateResult.md
- docs/type-load.md
- docs/type-moduleIdentifier.md
This adds docs on how you can write your own plugin. Includes a short example of an Image preloading plugin.
> Document on how to write a plugin

- package.json
> Upgrade to system-npm 0.6.10

- ext/npm-convert.js
- ext/npm-utils.js
- ext/npm.js
- package.json
- test/ext/npm.js
> Upgrade to system-npm 0.6.17

- docs/scheme-tilde.md
> Document the ~ scheme

- docs/type-metadata.md
- ext/npm-extension.js
- package.json
> Conditionally add Buffer shim when used

- docs/steal-module.md
- docs/steal.md
> Adds docs for script tag=steal-module

- ext/npm-convert.js
- package.json
> Better npm warnings

- ext/npm-extension.js
- ext/npm-utils.js
- package.json
> Upgrade to system-npm 0.6.20

- ext/npm-load.js
- package.json
> Adds process.version

- docs/system-lessOptions.md
Feature added to steal-less in PR [#26](https://github.com/stealjs/steal-less/pull/26)
> Documenting plugins option

- ext/less.js
- package.json
- test/ext/less.js
> Upgrade to latest steal-less with async xhr

- docs/module-npm.md
- docs/pages/quick-start.md
- docs/pages/why.md
> Document which folder is being created in the quickstart

- ext/npm-load.js
- package.json
> Prevent child package bundles from overwriting parent

- ext/npm-load.js
- package.json
> Update system-npm to 0.6.29

- ext/npm-crawl.js
- package.json
> Upgrade to system-npm 0.6.30

- docs/pages/contributing.md
> Delete build step in contributing documentation

- package.json
- steal.js
> Upgrade to steal-es6-module-loader 0.17.10

- docs/pages/babel.md
- docs/pages/changelog.md
- docs/pages/circular.md
- docs/pages/configuration.md
- docs/pages/contributing.md
- docs/pages/migrating.md
- docs/pages/production.md
- docs/pages/roadmap.md
- docs/pages/why.md
- docs/pages/writing-plugins.md
- docs/stealjs.md
> Add documentation on circular dependencies

- docs/pages/quick-start.md
> remove npmAlgorithm mention in the Quick Start guide

- docs/pages/progressive-loading.md
This adds the myhub training as the new progressive loading guide.
For #866
> Add the progressive loading guide

- docs/steal.md
- docs/stealjs.md
Moved ecosystem group from steal to stealjs md.
> Docs ecosystem

- docs/pages/production.md
- docs/pages/progressive-loading.md
- docs/pages/quick-start.md
> Change documentation to use the packaged steal.production.js

- docs/pages/production.md
- docs/pages/progressive-loading.md
> Use 2 argument form for stealTools.build

- docs/pages/progressive-loading.md
> Use line highlighting for the progressive loading guide

- docs/steal.md
Kinda related to canjs/can-compile#52
> Use v2.canjs.com in the example

- docs/steal.md
This reverts commit c3631fa2a8b749a47d0125506c562023317d45f1.
> Revert "Use v2.canjs.com in the example"

- docs/pages/changelog.md
This adds a changelog for the 1.0 changes.
> Changelog for 1.0

- docs/pages/progressive-loading.md
> Update the progressive loading guide to use the "plugins"

- ext/npm-crawl.js
- package.json
This fixes a race condition when setting "plugins" configuration on a
progressively loaded package.json. This fixes
https://github.com/stealjs/steal/issues/957
Original PR in steal-npm: https://github.com/stealjs/steal-npm/pull/210
> Upgrade to steal-npm to fix race condition

- docs/type-metadata.md
> Add docs for meta.globals option

- docs/config-cacheKey.md
- docs/config-cacheVersion.md
This adds documentation for the cache bust extension. Closes #1034
> Document the cache bust extension

- package.json
> chore(package): update buffer to version 5.0.4

- ext/npm-crawl.js
- package.json
The new patch release fixes a problem with package.json dependencies loading.
> Update steal-npm extension

- ext/npm-extension.js
- test/npm/bower/node_modules/steal/ext/npm-extension.js
- test/npm/steal_npm_helpers/dev.html
- test/npm/steal_npm_helpers/package.json
- test/npm/test.js
Closes #1069 
@matthewp is this what you had in mind?
> Provide an API to register pre loaded npm packages

- test/decorators/cellphone.js
- test/decorators/package.json
- test/test.js
> Test babel decorators plugin with Steal works

- package.json
> chore(package): update qunit to version 0.9.3

- Gruntfile.js
- package.json
- test/live_reload/basics/dep.js
- test/live_reload/basics/index.html
- test/live_reload/basics/main.js
- test/live_reload/demo/config.js
- test/live_reload/demo/other.js
- test/live_reload/demo/test.html
- test/live_reload/demo/test.js
- test/live_reload/package.json
- test/live_reload/retry/index.html
- test/live_reload/retry/main.js
- test/live_reload/unit.html
- test/live_reload/unit.js
- test/npm/live-reload/dev.html
- test/npm/live-reload/main.js
- test/npm/live-reload/package.json
- test/npm/steal-live-reload.html
- test/npm/test-live-reload.js
Closes #1088 
@matthewp I did not add the tests to saucelabs, these tests running the live-reload server don't play together fine. Tests run if I run each script but with both back to back the last one fails :/
> Move live-reload into core

- docs/config-babelOptions.md
> Update babelOptions documentation

- ext/live-reload.js
- test/live_reload/unit.js
- test/test-pages-urls.js
Closes #1163
Also enables the live-reload unit tests in CI.
> Log an error when unable to connect to ws server

- docs/pages/contributing.md
- Update repositories urls
- Update steps to generate the website
- Update test example to use `QUnit.test`
- Remove references to SystemJS and the es6ml
- Update explanation about StealJS code structure
Closes #1146
> Multiple updates to the Contributing guide

- docs/pages/progressive-loading.md
This replaces the repos widget with a weather widget instead.
The guide is updated and the app has been tested. Closes #1171
> Update progressive loading guide with weather widget

- docs/scheme-tilde.md
- ext/npm-convert.js
- ext/npm-utils.js
- test/npm/import_test.js
Also replaces `startsWithTildeSlash` with `isInHomeDir`  Replaces https://github.com/stealjs/steal/pull/1141
@matthewp is this PR on the right track?  Where would I add tests for this?
> Add homeAlias option

- docs/pages/progressive-loading.md
fixes the issues listed in #1188
> minor fixes for progressive loading

- docs/pages/babel.md
> Remove outdated note about babel plugins/presets

- test/saucelabs.js
> Change Saucelabs iOS to appium 1.6.3

- docs/pages/babel.md
Minor docs change for Babel options page.
> Docs: minor update for babel page #1192

- docs/pages/progressive-loading.md
- docs/pages/project-exporting.md
> Use double quotes in html attributes

- package.json
> chore(package): update testee to version 0.5.1

- ext/npm-crawl.js
- test/npm/normalize_test.js
> Descriptive version mismatch error

- ext/npm.js
- steal.production.js
- test/ext/npm.js
- test/npm/bower/node_modules/steal/steal.production.js
- test/npm/conditionals/package.json
- test/npm/git_ranges/package.json
- test/npm/import_test.js
> Throw when package.json is missing name/version fields

- package.json
Closes #1167 
Once this is merged I'm going to update https://github.com/stealjs/steal/wiki/Release-Process
> Remove "release" package

- .travis.yml
> Stop running tests on Node.js 0.12.x

- docs/pages/quick-start.md
> Fix typo "load import" in quick-start.md

- docs/pages/progressive-loading.md
> Show full package.json content with diff highlight

- docs/config-jsonOptions.md
> - fixed typo

- docs/config-depsbundle.md
- docs/config-devbundle.md
This adds the depsBundle and devBundle configuration docs. These will be
linked to from the new Development Bundles topic.
> Document the deps-bundle and dev-bundles configuration values

- .npmignore
ignore all unnecessary folders/files that users are not interested in when using npm.
close #1286
> adds a npmignore file.

- package.json
- scripts/copy.js
- test/npm/package.json
- test/npm/test.js
- test/saucelabs.js
> Remove jquery-ui

- ext/babel-code-frame.js
- test/node_test.js
This updates your code-frame dependency so that the errors pass through
correctly in Node.
> Update code-frame so that it will run in Node

- ext/npm-crawl.js
- test/npm/import_test.js
- test/npm/normalize_test.js
This improves the error messaging and includes a link to documentation
about it. Closes #1346
> Improve the error message on mismatched package versions

- .travis.yml
- test/saucelabs.js
- Node: 6, 8 and latest stable
- Brower: IE11+
> Update supported environments

- ext/npm-extension.js
- test/npm/import_test.js
> Make folder/index convention work in dev bundles / production mode

- ext/npm-utils.js
- test/mjs/another.js
- test/mjs/dev.html
- test/mjs/is-js.js
- test/mjs/is-mjs.mjs
- test/mjs/main.mjs
- test/mjs/other.js
- test/mjs/package.json
- test/mjs/uses-another.js
- test/test.js
> Add support for importing with the .mjs extension

- docs/config-env.md
> Document possible values of steal.loader.env

- .travis.yml
- package.json
- test/init_error/dev.html
- test/parse_errors/dev.html
- test/saucelabs.js
- test/syntax_errs/build.html
This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/cherifGsoul/def29ecbfa9ff53b859d466c7929870c**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.
> Migrate to use Xenial in Travis

- ext/npm-utils.js
- test/npm/normalize_main-config_test.js
> Support the forward slash behavior in pkg.main
