stealjs/steal

docs/pages/quick-start.md, docs/stealjs.md
Moved Quick Start to a separate file and removed the content from stealjs.md. And added Quick Start to the Guides navigation as the second item after Why StealJS. 
Also updated several details on Quick Start
=> Moved Quick Start to separate file and update stealjs overview page.

docs/pages/quick-start.md
Add simple http-server so users can easily view index.html in the browser.
Update npm install section - removes grunt-cli and http-server from dev-dependencies and makes them global.
Other minor updates to working
=> Quick Start guide update

src/startup.js
This gets rid of the "your app loaded successfully" message which creates noise during builds
and isn't something useful anyways, really only useful for debugging steal.
=> Remove loaded successful message

docs/pages/quick-start.md
This fixes the link to npm/http-server and turns the URLs to localhost:8080 into links.  They might as well be clickable.
=> Fixing links

docs/pages/contributing.md
This adds documentation on what is needed to get a Windows environment set up so that you can run the tests. Closes out https://github.com/bitovi/steal-tools/issues/122
=> Document developing with Windows

ext/npm-extension.js, ext/npm.js, package.json, test/ext/npm.js
This updates system-npm which has an override for config which will convert map and path names when belonging to a package.
=> Update npm to use config override

ext/less.js
To create sourceMaps during dev the appropriate option is set by steal-tools. But we still need to store the created map somewhere, so we're going to put it on `load.metadata.map`.
=> Create sourceMaps for less during the build

src/end.js, src/startup.js
Instead of logging inside of startup, log where startup is called in the browser. This prevents noisy errors during watch mode when a file doesn't exist (which isn\'t a problem in that scenario). Fixes #394
=> Move error logging to where startup is called

bower.json, docs/module-bower.md, docs/module-npm.md, ext/bower.js
This upgrades the local `ext/bower.js` to be `0.2.0`. Includes the addition of `system.bowerIgnore` and `system.main`. Documentation for these features is included.
=> Use system-bower 0.2.0

ext/bower.js
system-bower 0.2.2 includes a fix to guard against bower.jsons that do not have a main.
=> Upgrade system-bower to 0.2.2

ext/npm.js, package.json, steal.production.js, test/ext/npm.js
system-npm 0.3.0 includes a fix for setting the main when the package name is included.
=> Upgrade to system-npm 0.3.0

docs/pages/contributing-windows.md, docs/pages/contributing.md
This adds further documentation that goes into more details for how to contribute on Windows.
Fixes https://github.com/stealjs/steal-tools/issues/289
=> Full instructions for setting up on Windows

ext/live-reload.js
This upgrades us to live-reload 1.1.1.  This version allows you to turn off live-reload with a configuration option: `System.liveReload = false;`. This was needed for the server side rendering live-reload feature.
=> Upgrade to live-reload 1.1.1

docs/live-reload-disposeModule.md, package.json
This upgrades to the latest system-live-reload and adds documentation on the new `live-reload.disposeModule` function.
Closes #498
=> Upgrade to live-reload 1.4 and document

docs/module-npm.md, docs/pages/quick-start.md, docs/pages/roadmap.md, ext/npm-crawl.js, ext/npm-extension.js, ext/npm-utils.js, ext/npm.js, package.json, test/ext/npm.js
This updates system-npm for npm3 support. Adds docs to the npm module explaining usage of `npmAlgorithm` to turn on npm3 support:
```json
{
"system": {
"npmAlgorithm": "flat"
}
}
```
Closes #521
=> Update system-npm for npm3 support

ext/css.js, package.json, test/ext/css.js
This version includes a check that `loader.isEnv` exists because the CSS plugin might be used by a project that is exported into a global (with steal-tools) in which case there is only a tiny loader shim that doesn't include isEnv.
=> Upgrade to steal-css 0.1.1

ext/npm-crawl.js, package.json
0.4.3 has a fix for how traversal happens after missing a package.json when using NPM3.
=> use system-npm 0.4.3

docs/type-metadata.md
This adds documentation on the sideBundle option that is used as a production optimization. Closes #557
=> Document sideBundle

src/config.js, src/startup.js, test/script-tag_wins/index.html, test/test.js
with https://github.com/stealjs/steal-tools/pull/370 now css files should loaded correctly and baseUrl should be not overwritten
https://github.com/stealjs/steal/blob/master/src/config.js#L324
this fix some of the problems with
stealjs/steal#578
=> Script tag wins against global steal object

main.js, src/startup.js, steal.js
if we are in production and dont added a `main` attribute to the script tag, we get a warning.
but the `main` is not needed if we have steal bundled with steal-tools `stealBundle = true`
this PR prevent to get a warning.
we can use this new feature to detect if steal is bundled in the file https://github.com/stealjs/steal-tools/pull/425
close #641
=> No main warning if steal is bundled

test/node_test.js
This adds a test that shows that when a module is imported that doesn't exist in the filesystem in Node, that import promise will be rejected.
=> Adds a test that shows imports rejecting in Node

docs/pages/quick-start.md
This updates the quick-start guide to only use the modern conventions; gets rid of grunt in favor of an npm script, gets rid of other unnecessary config.
Part of #664
=> Update the quick-start guide to use modern conventions

docs/pages/configuration.md, docs/pages/migrating.md, docs/system-config.md
Added a guide that explains how to configure Steal in your package.json, and with some of the most common usages of Steal config.
=> Add a guide on configuration

docs/module-loader.md, docs/module-steal-clone.md
Updating the @loader docs; it's no longer true that it's used primarily by config. Since users don't write their own stealconfigs any more it's use can better be explained with regard to use with steal-clone.
=> Updating the @loader docs

docs/type-moduleName.md
This improves the documentation on moduleNames. I think this does a better job of explaining why they are important, as well as distinguishing moduleNames from moduleIdentifiers.  Also it explains the part of an npm moduleName since these are commonly part of Steal projects now.
=> Document moduleNames

docs/system-babelOptions.md, test/jsx/dev.html, test/jsx/main.js, test/jsx/package.json, test/test.js
In 1.0.0 jsx will be enabled by default, this adds a test to verify that this is the case.
Closes #686
=> Add test showing jsx is enabled by default

ext/npm-load.js, package.json, test/bower/npm/package.json, test/npm/bower/package.json, test/npm/package.json
This is to fix inconsistencies and potential double-loading where package name is used some times, and some times not.
=> npm plugin always forces System.main to have package name

docs/pages/loading-from-cdn.md, docs/pages/production.md
Closes https://github.com/stealjs/steal/issues/747.
=> Adding docs showing how to load scripts from a CDN

docs/system-cssOptions.md
adds docs for the new `cssOptions` 
https://github.com/stealjs/steal-css/pull/15
related to https://github.com/stealjs/steal/issues/261
=> add docs for cssOptions

docs/system-babelOptions.md
document which are the default babel-options set by steal
this PR is the last part for closing https://github.com/stealjs/steal/issues/772
=> babelOptions docs

ext/npm-convert.js, ext/npm-crawl.js, ext/npm-extension.js, ext/npm-utils.js, ext/npm.js, package.json, steal.production.js, test/ext/npm.js
This change makes it so that, when using the npm plugin, your first
level dependencies are no longer crawled. This means any plugins that
you use will need to be explicitly added in the steal.plugins
configuration:
```json
"dependencies": {
"steal-less": "1.0.0"
},
"steal": {
"plugins": ["steal-less"]
}
```
Using this config, steal will know to fetch steal-less' package.json,
which will cause the configuration to be applied.
=> npm plugin no longer crawls the first-level deps

test/test-sauce-labs.js
This adds Chrome and Firefox to be tested with OSX, in addition to the
already-tested Windows.
=> Adding OSX testing for Chrome/FF

ext/npm-crawl.js, package.json
This fixes https://github.com/stealjs/steal/issues/957
When we progressively load a package we also load in `plugins`
configuration it has. This configuration should be treated not as from
the root package, because doing so has been causing it to be looked up
from too deep of a folder. This closes #957
=> Fix progressively loaded plugins configuration

ext/npm-utils.js, package.json
steal-npm 1.0.3 includes a fix for setting configuration on recursive
objects. This manifests when using the `instantiated` configuration and
the value is some type of object that points back to itself.
=> Upgrade to steal-npm 1.0.3.

ext/npm-crawl.js, ext/npm-extension.js, package.json
steal 1.0.4 includes a fix for a bug when 2 versions of a package exists
in production.
=> Upgrade to steal-npm 1.0.4

docs/pages/progressive-loading.md
This updates the progressive loading guide with some fixes to issues I
found while giving a training. They are:
* Inconsistent string usage between two versions of myhub.js
* Updating the main myhub.js to load the puppies page inside of the Build Production... section, so I moved it to before that section.
* In the Exporting... section it was using the `system` property instead
* of the `steal` property.
Closes #1002
=> Update progressive loading guide

docs/module-steal-clone.md, ext/steal-clone.js, test/ext-steal-clone/default-export-usedefault/index.html, test/ext-steal-clone/default-export-usedefault/main.js, test/ext-steal-clone/default-export/index.html, test/ext-steal-clone/default-export/main.js, test/test.js
Previously to override a default export with steal-clone, you had to do:
```
clone({
'jquerty': {
default: {},
__useDefault: true
}
})
```
With this change, you do not need to pass `__useDefault` and steal-clone will set it for you.
Closes https://github.com/stealjs/steal/issues/985.
=> Simplify using steal-clone with default exports

package.json, src/trace/trace_test.html
remove `steal-qunit` from steal's `steal.npmDependencies` because that cause loading `steal-qunit` all the time.
make the tests working again by adding some paths and mapping.
this PR is blocked by https://github.com/stealjs/steal-qunit/issues/22
the `trace-test.html` will never start
=> refactor steal-trace tests

.gitignore, ext/npm-extension.js
This bug depends on precise loading timing that I was unable to recreate
in a test. What needs to happen is module A and B need to load the dep
at the exact same time, with module B getting an incorrect version the
first time, and module A using that incorrect version in its normalize
resolution.
This fixes #1075
=> Use resolutions to determine which pkg version to use.

ext/npm-crawl.js, test/npm/normalize_test.js
When resolving a change package, include its devDependencies in the
equation. This way, if a child package tries to load a devDependency
we'll at least try to load it (it may be installed by a different
module).
Fixes #1079
=> Include devDependencies when resolving child package's deps

ext/npm-crawl.js, ext/npm-extension.js, test/npm/normalize_test.js
This tightens when we consider a devDependency to be part of the
dependencyMap. This map is used for a few things in the npm plugin. We
only want to include devDependency in this map when trying to normalize
a name. This changes the method so that it accepts a boolean that
decides where devDependencies should be included or not, so that it is
restricted to just that use case.
Fixes #1086
=> Tighten restriction on use of devDependencies

docs/pages/progressive-loading.md
- Disable http-server caching
- Install all npm modules as dev dependencies
- Update QUnit async tests and assertions
=> Updates to the guide after last revision

ext/npm-convert.js, ext/npm-crawl.js, ext/npm-extension.js, ext/npm.js, test/npm/bower/node_modules/steal/ext/npm-convert.js, test/npm/import_test.js, test/npm/test.html
This change makes it possible so that you can load dependencies from
which you do not actual depend on.
Meaning if you have:
```js
require("jquery");
```
In your code, but your package does not directly depend on `jquery`,
then it is possible you will load jquery from npm anyways; if jquery
happens to exist within any parent package.
Closes #971
=> Allow loading packages that are not direct dependencies

.jshintrc, test/ext-steal-clone/basics/index.html, test/ext-steal-clone/basics/main.js, test/ext-steal-clone/config-separation/index.html, test/ext-steal-clone/config-separation/main.js, test/ext-steal-clone/default-export-usedefault/index.html, test/ext-steal-clone/default-export-usedefault/main.js, test/ext-steal-clone/default-export/index.html, test/ext-steal-clone/default-export/main.js, test/ext-steal-clone/fetch-cache/index.html, test/ext-steal-clone/fetch-cache/main.js, test/ext-steal-clone/leak/index.html, test/ext-steal-clone/leak/main.js, test/ext-steal-clone/multiple-overrides/index.html, test/ext-steal-clone/multiple-overrides/main.js, test/ext-steal-clone/npm-extension/index.html, test/ext-steal-clone/npm-extension/main.js, test/ext-steal-clone/prior-import/index.html, test/ext-steal-clone/prior-import/main.js, test/ext-steal-clone/relative-import/index.html, test/ext-steal-clone/relative-import/main.js, test/ext-steal-clone/relative-override/index.html, test/ext-steal-clone/relative-override/main.js, test/steal_clone_test.js, test/test.js
Seemed like the perfect candidate to move out of the main test file
- Remove `asyncTest` in favor of QUnit's async workflow
=> Move steal-clone extension tests into file

src/system-extension-contextual.js
If a contextual module is defined passing a string as the `definer` parameter, the `pluginLoader` needs to be used to dynamically load the `definer` function; otherwise steal-tools won't build the app.
Fixes this test https://travis-ci.org/stealjs/steal-tools/jobs/218230746#L1302
Closes #952
=> Use pluginLoader in contextual extension

ext/npm-crawl.js, test/npm/import_test.js
In #1117 we made it so that we fetch a package by name even if not a direct dependency. However, this can cause unwanted loading in the case where a child package has a devDependency (which will not be downloaded to node_modules). This prevents loading such devDependencies. Closes #1145
=> Prevent unwanted global package name loading

package.json
There are no node qunit tests
Close https://github.com/stealjs/steal/pull/1096 after merging.
=> Remove qunit (node) dependency

ext/live-reload.js, test/live_reload/unit.js, test/npm/load_test.js, test/saucelabs.js
When using the simple signature for reload.dispose:
```js
reload.dispose(function(){
// teardown stuff here
});
```
Support this by firing the dispose event on the correct module; the contextual module using `reload`.
Closes #1172
=> Call dispose callback when disposing a module

ext/live-reload.js, test/live_reload/unit.js
This makes it so that the live-reload extension is cloneable, and
therefore doesn't cause errors when used with steal-clone in tests.
Closes #1213
=> Make the live-reload extension cloneable

src/loader/lib/transpiler.js, src/loader/loader-sans-promises.js, src/loader/loader.js, steal-sans-promises.js, steal.js
This changes a couple of references of `mod.default` to `mod["default"]` for IE9 compat. Closes #1216
=> .default -> ["default"]

ext/npm-crawl.js, test/npm/normalize_test.js
The logic to get the `package.json` was stopping when a parent with an incompatible version was found, this causes some issues where steal would fetch the file in an incorrect location. Instead, the crawling should continue looking for parents where the file might be located.
Closes #1224
=> Continue crawling when a incompatible parent is found

ext/npm-crawl.js, steal-sans-promises.production.js, steal.production.js, test/npm/bower/node_modules/steal/steal.production.js, test/npm/test.js
Closes #1228 
So, we already faced this problem before... I remember skipping this test while I was migrating steal-npm but forgot to file an issue to check why it was failing.
The issue is caused by the following scenario (in the test):
// package.json
```json
dependencies: {
"@cycle/core": "^6.0.0",
"rx": "^4.0.7"
}
```
// cycle/core's package.json
```json
devDependencies: {
"rx": "4.0.6"
},
peerDependencies: {
"rx": "*"
}
```
When the npm extension is normalizing `@cycle/core ->rx`, it grabs the version inside `devDependencies` which is not compatible with the one in the top package.json.
https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/ext/npm-extension.js#L123
That line is the issue since it uses `getFullDependencyMap` which uses the packages inside …
=> Fixes bug loading peer deps that are dev deps too

ext/npm-crawl.js, test/npm/normalize_test.js
TL; DR 
The error message looks like this now:
```
Did not find [pkg.origFileUrl],
Unable to find a compatible version of [pkg.name]
Wanted: [pkg.version]
Found: [found.version]
```
Long version.
The previous version was printing out all the package names that had [pkg.name] (the one failing to load) as a dependency, regardless of which version they depended on. That's why it was printing out a lot of crazy stuff in Kevin's scenario.
I played with the method (maybe a lot longer that I should have) that gets the parent names to make sure it matches a given version (1)
The thing is, the package that depends on the version causing the error won't be in the npm extension state because steal throws when it's loading it 😄 , so what we can do is tell the user what packages depend on the last …
=> Simplify mismatch version error message

README.md, docs/module-npm.md, docs/module-steal-clone.md, docs/pages/changelog.md, docs/pages/configuration.md, docs/pages/contributing.md, docs/pages/migrating.md, docs/pages/project-exporting.md, docs/pages/why.md, docs/steal.md, docs/type-moduleIdentifier.md, docs/type-moduleName.md, ext/npm-extension.js, test/npm/import_test.js, test/npm/npm-deep/node_modules/steal/ext/npm-extension.js
Also fixed NPM -> npm and “capabilities” typo in the README.
Fixes https://github.com/stealjs/stealjs/issues/34
=> Add plugins configuration documentation

.travis.yml, test/npm/normalize_main-config_test.js, test/npm/normalize_plugins-config_test.js, test/npm/normalize_test.js
This restructures the npm normalize tests, putting the different
QUnit.modules into their own test files to make it easier to add new
tests.
Also adds a breaking test for #1208 (currently skipped)
=> Restructure npm normalize tests

ext/npm-convert.js, ext/npm-extension.js, test/npm/normalize_test.js
Closes #1208
The app in the original issue runs ok with this branch https://github.com/m-mujica/steal-preact-compat-map
=> Apply mappings when left-side is not a pkg but right-side is.

ext/live-reload.js, steal-sans-promises.production.js, steal.production.js
Closes canjs/can-view-parser#75
=> Fix issue breaking live-reload when used with dynamic-import

ext/npm-convert.js, test/npm/normalize_test.js
This prevents the `buildConfig`, which is used to have a special
configuration during the build, from overriding the rest of a package's
configuration, which needs to be carried over to production.
Fixes #1319
=> Prevents buildConfig from overriding package's configuration

ext/npm-extension.js, ext/npm-utils.js, test/live_reload/package.json, test/npm/import_test.js, test/npm/utils_test.js
This prevents the 'Is this an npm module not saved' error message when a
file is missing from the root package. This error is problematic because
it is never the problem that a dependency is not saved, in this
circumstance. Fixes #1332
=> Prevent 'Is this an npm module not saved' error

ext/live-reload.js
live-reload creates a promise by waiting on `steal.done()` before doing
its WebSocket connection. Since this is a new promise, if steal.done()
rejects, Node will show an unhandled rejection error. To fix we just
ignore errors in this newly created promise; the errors will be
handled elsewhere.
Closes #1348
=> Prevent unhandled rejections caused by live-reload

docs/module-live-reload.md, ext/live-reload.js, test/live_reload/unit.js
This fixes #1350. If there is an error during live-reload, the `reload`
callback function will include the Error.
```js
import reload from "live-reload";
reload(function(err){
if(err) {
displayErrorMessage(err);
} else {
// Do whatever is normal
}
});
```
=> reload(callback) syntax now returns an error

ext/live-reload.js, src/loader/lib/loader.js, src/loader/loader-sans-promises.js, src/loader/loader.js, steal.js, test/live_reload/unit.js
During live-reload we call `loader.delete()` to delete a module from the
registry. However we always first check if it is in the registry. This
change makes it so that we always call 'delete' and delete removes the
item from the `failed` array, if it exists.
Fixes #1357
=> When a module is deleted, ensure any 'failed' records are removed

ext/npm-extension.js, test/npm/normalize_test.js
"Late" config is config that is set not part of the loading process but
stuff that is set later (like internally within steal-tools). This
should not be resaved because it is not part of a package's own
configuration and should not be reflected in production.
=> Don't save the package.json of config set "late"

ext/npm-extension.js, test/npm/normalize_test.js
Currently this configuration is copied over directly in steal-tools
(yuck!). With the new hook we no longer need to do that. This implements
_newLoader so we can get rid of that noise within steal-tools.
=> Implement the _newLoader hook for the npm extension

docs/module-npm.md
pnpm uses a nested node_modules structure, so it’s nice to explicitly mention it in the docs so people can more easily find this config option.
=> Add note about pnpm to the npmAlgorithm docs

ext/npm-extension.js, test/npm/normalize_test.js
This fixes the issue presented in #1426 where a default map exists but
is overridden by config in `envs`.
Closes #1426
=> Make envs map override configuration work

ext/npm-crawl.js, test/npm/helpers.js, test/npm/normalize_test.js
Loading Node builtins should happen automatically, because steal's own
package.json is loaded up-front. This fixes the behavior.
Closes #1428
=> Correctly load steal's package.json for Node builtins

docs/config-configMain.md, docs/config-depsbundle.md, docs/config-devbundle.md, docs/config-env.md, docs/config-loadBundles.md, docs/config-main.md, docs/module-npm.md, docs/scheme-tilde.md, docs/steal-module.md
This improves the main configuration docs. It gives the various
signatures (ways that the main can be loaded), explains why you might
omit the main, and documents the warning when you don't load a main by
mistake.
Closes #1423 and #1424
=> Better document the main configuration

ext/npm-extension.js, test/electron/electron.html, test/electron/package.json
this fixes `locate` in an npm project that is using Electron. Previously
`locate` would incorrectly encode the URL because it thought it was not
running in a browser.
Fixes #1451
=> Fix using electron with an npm project

ext/npm-extension.js, test/npm/normalize_test.js
This fixes a case where someone might use `../` to point to the
package.json main *and* the package.json contains `./` in it.
=> Fix additional case of ../ usage

ext/npm-utils.js, test/npm/import_test.js, test/saucelabs.js
Dependencies that use git+ssh can create moduleNames that interfere with
steal's moduleName parsing. URLs such as:
`git+ssh://git@example.com/company/my-lib.git#c23dr61`
Are problematic because they contain both an `@` and a `#` which have
special meaning.
The solution here is to encode the version number. For normal versions
like 1.0.0 this will not change anything. Only for these weird versions
that are actual URLs.
Fixes #1324 
This is being merged into the `1.0` branch first, then will be done to master.
=> Correctly encode git+ssh dependencies

src/extension-tree-shaking.js
use `compact: false` for transforming code.
see https://github.com/stealjs/steal-tools/issues/1071 for more information
close https://github.com/stealjs/steal-tools/issues/1071
=> use compact: false

ext/steal-clone.js, test/test.js, test/tree-shake-complex/site.html, test/tree_shake/anon.html, test/tree_shake/bundle.html, test/tree_shake/dev.html, test/tree_shake/race.html, test/tree_shake/steal-clone.html, test/tree_shake_reexport/dev.html, test/tree_shake_reexport/no-tree-shaking.html, test/tree_shake_reexport/tree-shaking-false.html
tree-shaken dep trees uses Sets to store information about used exports.
When steal-clone copies configuration, it attempts to clone that
configuration. This makes it so that it detects Sets, and clones those
correctly. Fixes #1470
=> Make steal-clone work with tree-shaken trees

ext/npm-extension.js, steal.production.js, test/npm_nested_import_errors/dep.js, test/npm_nested_import_errors/dev.html, test/npm_nested_import_errors/main.js, test/npm_nested_import_errors/package.json, test/test.js
This adds the importer file of a missing module to the error message by prepending the stack to error.
Fixes https://github.com/stealjs/steal/issues/1463
=> warn with the importer in case of missing module

package.json
Ran into some issues with the files lookup, it seems passing only the directories is better than globbing. I intentionally added a param reassign to make sure eslint was indeed working.
```
npm run lint
> steal@2.2.2 lint /Users/mmujica/Projects/steal
> eslint src ext
/Users/mmujica/Projects/steal/src/json/json.js
4:2  error  Assignment to function parameter 'loader'  no-param-reassign
✖ 1 problem (1 error, 0 warnings)
```
=> Fix security vulnerability introduced by eslint<4.18.2
